# Generated by Django 3.0.7 on 2020-06-27 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200627_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='creation_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='report',
            name='update_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
